#ifndef WAFEL_IPC_COMMANDS_H
#define WAFEL_IPC_COMMANDS_H

#define IOCTL_GET_API_VERSION 0x1
#define IOCTL_SET_FW_PATH 0x2
#define IOCTLV_WRITE_MEMORY 0x3
#define IOCTLV_EXECUTE 0x4

#define WAFEL_API_VERSION 0x010000 // v1.0.0

#endif // WAFEL_IPC_COMMANDS_H
