#ifndef WAFEL_IPC_COMMANDS_H
#define WAFEL_IPC_COMMANDS_H

#define IOCTL_SET_FW_PATH 0x1
#define IOCTL_GET_API_VERSION 0x2

#define WAFEL_API_VERSION 0x01000000 // v1.0.0.0

#endif // WAFEL_IPC_COMMANDS_H
